---
# Liam Nolan 2017 (c) BSD 2-Clause
#
- name: restart httpd
  systemd:
      name: "httpd.service"
      state: "restarted"
- name: reload httpd
  systemd:
      name: "httpd.service"
      state: "reloaded"
