---
# Liam Nolan 2017 (c) BSD 2-Clause
# 

- name: install /etc/sysctl.d/
  copy: 
      src: "assets/etc/sysctl.d/"
      dest: "/etc/sysctl.d/"
      mode: "u=rw,g=r,o=r"
      backup: yes
      remote_src: no

- name: assemble /etc/sysctl.conf
  assemble: 
      src: "/etc/sysctl.d/"
      dest: "/etc/sysctl.conf"
      mode: "u=rw,g=r,o=r"
      backup: yes
      remote_src: yes

# pf configuration 
- name: /etc/pf.conf
  copy: 
      src: "assets/etc/pf.conf"
      dest: "/etc/pf.conf"
      mode: "u=rw"
      backup: yes
  notify:
    - pf reload

- name: "/etc/anchor_{{ item }}" 
  copy: 
      src: "{{ item }}"
      dest: "/etc/"
      mode: "u=rw"
      backup: yes
  with_fileglob: "assets/etc/anchor_*"
  notify:
    - pf reload

- name: "/etc/hostname.{{ item }}"
  copy: 
      src: "{{ item }}"
      dest: "/etc/"
      mode: "u=rw"
      backup: yes
  with_fileglob: "assets/etc/hostname.*"
  notify:
    - hostname_if change

