---
# Liam Nolan 2017 (c) BSD 2-Clause
# baseline configuration for openbsd61 servers on lan

- hosts: openbsd_servers
  remote_user: ansibleadm
  become: yes
  become_method: doas

  tasks:
    # install pf.conf
    - name: install pf.conf
      copy:
        src: 'baseline_openbsd/etc/pf.conf'
        dest: '/etc/pf.conf'
        owner: 'root'
        group: 'wheel'
        mode: 0600
        validate: 'pfctl -n -f %s'
      register: pf

    - name: install doas.conf
      copy:
        src: 'baseline_openbsd/etc/doas.conf'
        dest: '/etc/doas.conf'
        owner: 'root'
        group: 'wheel'
        mode: 0600
        
    - name: install login.conf
      copy:
        src: baseline_openbsd/etc/login.conf
        dest: /etc/login.conf
        owner: 'root'
        group: 'wheel'
        mode: 0644

    - name: install resolv.conf
      copy:
        src: baseline_openbsd/etc/resolv.conf
        dest: /etc/resolv.conf
        owner: 'root'
        group: 'wheel'
        mode: 0644

    - name: install sysctl.conf
      copy:
        src: baseline_openbsd/etc/sysctl.conf
        dest: /etc/sysctl.conf
        owner: 'root'
        group: 'wheel'
        mode: 0644

    - name: install sshd_config
      copy:
        src: baseline_openbsd/etc/ssh/sshd_config
        dest: /etc/ssh/sshd_config
        owner: 'root'
        group: 'wheel'
        mode: 0644
      register: sshd_config

    - name: install ssh moduli
      copy:
        src: baseline_openbsd/etc/ssh/moduli
        dest: /etc/ssh/moduli
        owner: 'root'
        group: 'wheel'
        mode: 0644
    - name: reload sshd if config changed
      command: "/usr/sbin/rcctl restart sshd"
      when: sshd_config.changed
    
    - name: reload pf if pf.conf changed (only rules so the connection does not drop)
      command: '/sbin/pfctl -F rules -f /etc/pf.conf'
      when: pf.changed
    
