---
# Liam Nolan 2017 (c) BSD 2-Clause
#
# default ntp servers (Canadian Pool)
remote_ntp_servers: ['0.ca.pool.ntp.org', '1.ca.pool.ntp.org', '2.ca.pool.ntp.org', '3.ca.pool.ntp.org']
# OpenNTPD uses https time as an additional constraint, some default servers are set here
openntpd_constraints: ['https://www.google.com', 'https://www.amazon.com', 'https://www.apple.com']
