# Liam Nolan 2017 (c)
---
- name: restart dnsmasq
  systemd:
      name: 'dnsmasq.service'
      state: "restarted"

# unbound fails (chroot problems, again...) using unbound-control reload
# or rcctl reload so I am just restarting it for now TODO fix
- name: reload unbound
  command: 'rcctl restart unbound'
