---
# Liam Nolan 2017 (c) BSD 2-Clause
#

- name: restart rsyslog
  systemd:
      name: "rsyslog.service"
      state: "restarted"

- name: reload sshd
  systemd:
      name: "sshd.service"
      state: "reloaded"

- name: reload sysctl
  command: "sysctl --system"

- name: openbsd sshd reload
  command: "/usr/sbin/rcctl restart sshd"

- name: pf reload rules
  command: '/sbin/pfctl -F rules -f /etc/pf.conf'

