# Liam Nolan 2017 (c)
---

- include: fedora25_baseline.yml
  when: ansible_distribution == "Fedora" and ansible_distribution_release == "Twenty Five"
- include: openbsd61_baseline.yml
  when: ansible_distribution == "OpenBSD" and ansible_distribution_version == "6.1"
