# Liam Nolan 2017 (c)
---

- include: fedora25_baseline.yml
  become_method: sudo
  become: yes
  when: ansible_distribution == "Fedora" and ansible_distribution_release == "Twenty Five"
- include: openbsd61_baseline.yml
  become_method: doas
  become: yes
  when: ansible_distribution == "OpenBSD" and ansible_distribution_version == "6.1"
- include: fedora25_baseline.yml
  become_method: sudo
  become: yes
  when: ansible_distribution == "CentOS" and ansible_distribution_release == "7"
