# Liam Nolan 2017 (c)
---

- include: ubuntu_baseline.yml
  become_method: sudo
  become: yes
  when: ansible_distribution == "Ubuntu" 

- include: fedora_baseline.yml
  become_method: sudo
  become: yes
  when: ansible_distribution == "Fedora" and ansible_distribution_release == "Twenty Eight"

- include: openbsd61_baseline.yml
  become_method: doas
  become: yes
  when: ansible_distribution == "OpenBSD" and ansible_distribution_version == "6.1"

- include: centos_baseline.yml
  become_method: sudo
  become: yes
  when: ansible_distribution == "CentOS" and ansible_distribution_major_version == "7"
