# Armorless-Visage 2017
---
- name: packages installed and updated 
  dnf: 
      name: "{{ item }}"
      state: latest
  with_items: "{{ system_packages }}"

- name: install /etc/samba/smb.conf
  copy: 
      src: "assets/smb.conf"
      dest: "/etc/samba/smb.conf"
      mode: "u=rw,g=r,o=r"
      seuser: "system_u" 
      serole: "object_r"
      setype: "samba_etc_t"
      backup: yes
      validate: "testparm %s"
  notify:
    - smb reload

# NOTE: bug with this module and systemd results in service not found errors
- name: start/enable system services
  systemd:
      name: "{{ item }}"
      state: "started"
      enabled: "yes"
      masked: "no"
  with_items: "{{ system_services }}"

- name:  firewalld ports
  firewalld:
      service: "{{ item }}"
      zone: "{{ firewalld_zone }}"
      permanent: yes
      state: enabled
  with_items: "{{ firewalld_services }}"


